myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from boards import views
from boards.forms import SignInForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('', auth_views.LoginView.as_view(template_name='signin/signin.html', authentication_form=SignInForm), name='signin'),
    path('signout/', auth_views.LogoutView.as_view(), name='signout'),
    path('home/', views.home, name='home'),
    path('upload_excel/', views.upload_excel, name='upload_excel'),
    path('teams/', views.teams, name='teams'),
    path('teams/<int:team_id>', views.view_team, name='view_team'),
    path('teams/new', views.create_team, name='create_team'),
    path('teams/<int:team_id>/edit', views.edit_team, name='edit_team'),
    path('teams/<int:team_id>/delete', views.delete_team, name='delete_team'),
    path('persons/new', views.create_person, name='create_person'),
    path('persons/<int:person_id>/edit', views.edit_person, name='edit_person'),
    path('persons/<int:person_id>/delete', views.delete_person, name='delete_person'),
    path('calendar/', login_required(views.CalendarView.as_view()), name='calendar')
]

myproject/boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

from datetime import datetime

# Create your models here.
class HRPerson(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Team(models.Model):
    name = models.CharField(max_length=100)
    hr_person = models.ForeignKey(to=HRPerson, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    email = models.EmailField(default='admin@admin.com')
    phone = models.IntegerField(default=12345678)
    is_support_person = models.BooleanField(default=False)
    team = models.ForeignKey(to=Team, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}({self.team.name})'

class BirthdayEvent(models.Model):
    person = models.ForeignKey(to=Person, on_delete=models.CASCADE)
    date = models.DateField(default=now)
    event_link = models.CharField(max_length=1000)

myproject/templates/team/create_team.html
{% extends 'base.html' %}
{% block content %}
<main class="form-signin">
  <form action="" method='POST'>
    <div class="mb-6">
      <h2>Create New Team</h2>
    </div>
    {% csrf_token %}
    {{ form }}
    {% if form.instance.pk is None %}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Create Team</button>
    {% else %}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Update Team</button>
    {% endif %}
  </form>
</main>
{% endblock %}

myproject/templates/team/teams.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-between bd-highlight mb-3">
  <div class="bd-highlight">
    <h3>Teams</h3>
  </div>
  <div class="bd-highlight">
    <a href="{% url 'create_team' %}">
      <button id="upload-excel" type="button" class="btn btn-warning float-right"><span><strong>Add Team</strong></span></button>
    </a>
  </div>
</div>

<div class="d-flex flex-row-reverse bd-highlight mb-2">
  <form class="form-inline my-2 my-md-0">
    <input class="form-control" type="text" placeholder="Search" aria-label="Search">
  </form>
  <img src="{% static 'img/search.svg' %}" class="searchicon">
</div>

<table class="table table-striped">
  <thead class="thead-green">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Team members</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for team in teams %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'view_team' team.id %}">{{ team.name }}</a></td>
        <td>{{ team.person_set.count }}</td>
        <td>
          <a href="{% url 'edit_team' team.id %}">Edit</a>
          <a href="{% url 'delete_team' team.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </tr>
  </tbody>
</table>

</div> <!-- /container -->

{% endblock %}

myproject/templates/team/view_team.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-between bd-highlight mb-3">
  <div class="bd-highlight">
    <h3>{{ team.name }}</h3>
  </div>
  <div class="bd-highlight">
    <a href="{% url 'create_person' %}">
      <button id="upload-excel" type="button" class="btn btn-warning float-right"><span><strong>Add Person</strong></span></button>
    </a>
  </div>
</div>

<div class="d-flex flex-row-reverse bd-highlight mb-2">
  <form class="form-inline my-2 my-md-0">
    <input class="form-control" type="text" placeholder="Search" aria-label="Search">
  </form>
  <img src="{% static 'img/search.svg' %}" class="searchicon">
</div>

<table class="table table-striped">
  <thead class="thead-green">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Birthday</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for person in persons %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ person.name }}</td>
        <!-- TODO: Fix display when email/phone not present -->
        <td>{{ person.email }}</td>
        <td>{{ person.phone }}</td>
        <td>{{ person.birthday }}</td>
        <td>
          <a href="{% url 'edit_person' person.id %}">Edit</a>
          <a href="{% url 'delete_person' person.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </tr>
  </tbody>
</table>

</div> <!-- /container -->

<div class="d-flex justify-content-center mb-2">
<nav aria-label="Page navigation example">
<ul class="pagination">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>
</nav>
{% endblock %}